### PR TITLE
fix: set default value to field's type during unmarshalling

### LINKED ISSUE #771: Error with non-string parameter's default values
### Prerequisites

- [x] I've searched the current open issues
- [x] I've updated to the latest version of Toolbox

### Toolbox version

main

### Environment

1. OS type and version: `Darwin Kernel Version 24.5.0: Tue Apr 22 19:54:29 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T6030 arm64`
2. How are you running Toolbox: 
  - As a downloaded binary `curl -O https://storage.googleapis.com/genai-toolbox/main/linux/amd64/toolbox`

### Client

1. Client: `curl`
2. Version: 
3. Example: If possible, please include your code of configuration:

Tools file:
```yaml
...
tools:
  search-rows:
    ...
    parameters:
      - name: "email"
        type: "string"
        description: "..."
      - name: "data"
        type: "string"
        description: "..."
        default: "row2"
      - name: "id"
        type: "integer"
        description: "..."
        default: 0
    ...
```

```bash
curl --location 'http://127.0.0.1:5000/api/tool/search-rows/invoke' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "..."
}'
```

This throws an error:
```
{"status":"Bad Request","error":"provided parameters were invalid: unable to parse value for \"id\": '\\x00' not type \"integer\""}
```

This is the same for more types as well eg. `"float"`. Seems like the `default` value provided in the `tools.yaml` is being parsed as a generic `Any` type, which ultimately makes the integer values (like `0` in this case) be parsed as `uint64`, which ultimately leads to this error.

### Expected Behavior

A success response with the provided `default` value of `0` being interpreted as an integer `0`.

### Current Behavior

Currently the integer value of `0` is being incorrectly casted as a `uint64` `0x0`.

### Steps to reproduce?

1. Write a tool with a parameter with `type` as `integer` and `default` as `0`
2. Invoke this tool without passing that optional parameter.

### Additional Details

I also tried by passing the `default` as `int!! 0` instead of just `0`, but it led to the same error.

### PR DESCRIPTION
**Pull request by Yuan325**
When go-yaml decode into CommonParameter with Default being an any type, int will be converted into []uint64.
It will fail the Parse() when the value is being used since it does not belong to either of the int types.

Unmarshal `default` value into each field's type directly.

Fixes #771

### CODE REVIEW

File: internal/tools/parameters.go [hunk 1]
```diff
@@ -527,10 +503,38 @@ func (p *StringParameter) Parse(v any) (any, error) {
...
+func (p *StringParameter) Manifest() ParameterManifest {
+	// only list ParamAuthService names (without fields) in manifest
+	authNames := make([]string, len(p.AuthServices))
+	for i, a := range p.AuthServices {
+		authNames[i] = a.Name
+	}
+	var required bool
+	if p.Default == nil {
+		required = true
+	}
```
Comment (kurtisvg) [inline internal/tools/parameters.go]: nit: Could this be `required := p.Default == nil` instead?

**Review by kurtisvg — APPROVED** [review]
