### PR TITLE
fix(tools/mongodb-find-one): ProjectPayload unmarshaling

### LINKED ISSUE #1153: cve-find-one returns invalid document length error
### Prerequisites

- [x] Search the [current open issues](https://github.com/googleapis/genai-toolbox/issues)

### Description:
When calling cve-find-one, I encountered the following error:
### Request
```json
{"cve-find-one": {"ip": "187.72.65.17"}}
```
### Response
```json
{"cve-find-one": "error populating options: error unmarshalling projection: invalid document length"}
```
### Expected behavior
Should return the CVE information for the given IP address.
### Actual behavior
Returns the error:
```bash
error unmarshalling projection: invalid document length
```

### Environment

- Method: cve-find-one
- Parameters: {"ip": "187.72.65.17"}
- Service version: please specify
- Deployment: please specify (e.g., Docker / local run)
Do you want me to also add a Possible Cause section so it looks more professional and helps maintainers troubleshoot faster?

### Code

_No response_

### Additional Details

_No response_

### PR DESCRIPTION
**Pull request by averikitsch**
## Description
---
Update mongodb find one to unmarshal projectpayload

## PR Checklist
---
> Thank you for opening a Pull Request! Before submitting your PR, there are a
> few things you can do to make sure it goes smoothly:
- [ ] Make sure you reviewed
  [CONTRIBUTING.md](https://github.com/googleapis/genai-toolbox/blob/main/CONTRIBUTING.md)
- [ ] Make sure to open an issue as a
  [bug/issue](https://github.com/googleapis/langchain-google-alloydb-pg-python/issues/new/choose)
  before writing your code!  That way we can discuss the change, evaluate
  designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)
- [ ] Make sure to add `!` if this involve a breaking change

🛠️ Fixes #1153

### CODE REVIEW

File: internal/tools/mongodb/mongodbfindone/mongodbfindone.go [hunk 1]
```diff
@@ -159,15 +159,14 @@ func getOptions(sortParameters tools.Parameters, projectPayload string, paramsMa
...
 
 	result, err := tools.PopulateTemplateWithJSON("MongoDBFindOneProjectString", projectPayload, paramsMap)
-
 	if err != nil {
 		return nil, fmt.Errorf("error populating project payload: %s", err)
 	}
 
 	var projection any
-	err = bson.Unmarshal([]byte(result), &projection)
+	err = json.Unmarshal([]byte(result), &projection)
```
Comment (duwenxin99) [inline internal/tools/mongodb/mongodbfindone/mongodbfindone.go]: Should we use bson's [unmarshal json function](https://github.com/googleapis/genai-toolbox/blob/15a1b67a9d4f2e34e5740f80e12f84926b4b2143/internal/tools/mongodb/mongodbfind/mongodbfind.go#L170) instead? We should probably keep these two implementations the same. Could you also help to correct the spelling error [here](https://github.com/googleapis/genai-toolbox/blob/15a1b67a9d4f2e34e5740f80e12f84926b4b2143/internal/tools/mongodb/mongodbfind/mongodbfind.go#L172) as well? Thank you!

Comment (averikitsch) [reply internal/tools/mongodb/mongodbfindone/mongodbfindone.go]: Thank you! Ready for re-review
