### PR TITLE
fix(source/cloud-sql-mssql): remove ip address field

### LINKED ISSUE #1549: Remove IP address from Cloud SQL SQL Server source
### Prerequisites

- [x] I've searched the current open issues
- [x] I've updated to the latest version of Toolbox

### Toolbox version

0.15.0

### Environment

1. OS type and version: (output of `uname -a`)
2. How are you running Toolbox: 
  - As a downloaded binary (e.g. from `curl -O https://storage.googleapis.com/genai-toolbox/v$VERSION/linux/amd64/toolbox`)
  - As a container (e.g. from `us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:$VERSION`)
  - Compiled from source (include the command used to build)

### Client

Gemini CLI

### Expected Behavior

IP address is not an input for Cloud SQL SQL Server source.

### Current Behavior

IP Address is label as a required input for the Cloud SQL SQL server source. However, any ip address works. The connector has uses localhost as an example, so this input most likely is not needed.

### Steps to reproduce?

1. ?
2. ?
3. ?
...

### Additional Details

_No response_

### PR DESCRIPTION
**Pull request by Yuan325**
## Description

Removing the `ipAddress` field since it is not an input for Cloud SQL SQL Server source. 

Kept the variable in Source's config but removed this variable from everywhere else in the code. This will PREVENT a breaking change since the validator won't flag it as an "extra field".

**Will have to update the following as well:**
(1) Cloud docs https://cloud.google.com/sql/docs/sqlserver/pre-built-tools-with-mcp-toolbox
(2) gemini-cli-extensions https://github.com/gemini-cli-extensions/cloud-sql-sqlserver

## PR Checklist

> Thank you for opening a Pull Request! Before submitting your PR, there are a
> few things you can do to make sure it goes smoothly:

- [x] Make sure you reviewed
  [CONTRIBUTING.md](https://github.com/googleapis/genai-toolbox/blob/main/CONTRIBUTING.md)
- [x] Make sure to open an issue as a
  [bug/issue](https://github.com/googleapis/genai-toolbox/issues/new/choose)
  before writing your code! That way we can discuss the change, evaluate
  designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)
- [x] Make sure to add `!` if this involve a breaking change

🛠️ Fixes #1549

### CODE REVIEW

File: internal/sources/cloudsqlmssql/cloud_sql_mssql.go [hunk 1]
```diff
@@ -49,16 +49,15 @@ func newConfig(ctx context.Context, name string, decoder *yaml.Decoder) (sources
 
 type Config struct {
 	// Cloud SQL MSSQL configs
-	Name      string         `yaml:"name" validate:"required"`
-	Kind      string         `yaml:"kind" validate:"required"`
-	Project   string         `yaml:"project" validate:"required"`
-	Region    string         `yaml:"region" validate:"required"`
-	Instance  string         `yaml:"instance" validate:"required"`
-	IPAddress string         `yaml:"ipAddress" validate:"required"`
```
Comment (averikitsch) [inline internal/sources/cloudsqlmssql/cloud_sql_mssql.go:57]: Should we keep the field listed here but deprecate it (similar to AuthSources) so it's not a breaking change?

File: internal/sources/cloudsqlmssql/cloud_sql_mssql.go [hunk 2]
```diff
@@ -125,7 +124,6 @@ func initCloudSQLMssqlConnection(ctx context.Context, tracer trace.Tracer, name,
 	url := &url.URL{
 		Scheme:   "sqlserver",
 		User:     url.UserPassword(user, pass),
-		Host:     ipAddress,
```
Comment (averikitsch) [inline internal/sources/cloudsqlmssql/cloud_sql_mssql.go:128]: I assume we don't need to set a default to localhost, right?

Comment (Yuan325) [reply internal/sources/cloudsqlmssql/cloud_sql_mssql.go:128]: Doesn't seem like it. I tested this and it worked without a host

File: internal/sources/cloudsqlmssql/cloud_sql_mssql.go (hunk 1 above)
Comment (Yuan325) [reply internal/sources/cloudsqlmssql/cloud_sql_mssql.go:57]: Removed the required flag but kept this field so validator won't throw an error. This variable will not be used in the code.

**Review by averikitsch — APPROVED** [review]
